version: '3.5'
services:

  user-mysql:
    image: mysql:5.7.21
    container_name: user-mysql
    hostname: user-mysql
    ports:
      - 3306:3306
    environment:
     - MYSQL_ROOT_PASSWORD=secret
     - MYSQL_DATABASE=userdb
     - MYSQL_USERNAME=root
     - MYSQL_PASSWORD=secret

  event-cassandra:
    container_name: event-cassandra
    hostname: event-cassandra
    image: cassandra:3
    ports:
      - 9042:9042
      - 7199:7199
      - 9160:9160

  zoo:
    image: zookeeper:3.4
    container_name: zoo
    hostname: zoo
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: zoo

  kafka:
    image: wurstmeister/kafka:0.11.0.1
    container_name: kafka
    hostname: kafka
    links:
      - zoo
    depends_on:
      - zoo
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: $HOST_IP_ADDR
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zoo:2181

  zipkin:
    image: openzipkin/zipkin:2.7.0
    container_name: zipkin
    hostname: zipkin
    ports:
      - 9411:9411