version: '3.5'
services:

  user-mysql:
    container_name: user-mysql
    image: mysql:5.7.22
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
     - MYSQL_ROOT_PASSWORD=secret
     - MYSQL_DATABASE=userdb
     - MYSQL_USERNAME=root
     - MYSQL_PASSWORD=secret
#  healthcheck:
#    test: ???
#    start_period: 20s

  event-cassandra:
    image: cassandra:3
    container_name: event-cassandra
    restart: unless-stopped
    ports:
      - 9042:9042
      - 7199:7199
      - 9160:9160
#  healthcheck:
#    test: ???
#    start_period: 20s

  zookeeper:
    image: confluentinc/cp-zookeeper:4.1.0
    container_name: zookeeper
    restart: unless-stopped
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    healthcheck:
      test: "echo stat | nc localhost $$ZOOKEEPER_CLIENT_PORT"
      start_period: 20s

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:4.1.0
    restart: unless-stopped
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_ADVERTISED_HOST_NAME:
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "9092" ]
      start_period: 20s

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin:2.7.0
    restart: unless-stopped
    ports:
      - 9411:9411
    healthcheck:
      test: "curl -f http://localhost:9411 || exit 1"
      start_period: 20s