spring:
  jpa:
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:mysql://${MYSQL_ADDR:localhost}:3306/userdb?autoReconnect=true&useSSL=false&useUnicode=yes&characterEncoding=UTF-8&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: secret
  cloud:
    stream:
      schema-registry-client:
        endpoint: http://${SCHEMA_REGISTRY_ADDR:localhost}:8081
      kafka:
        binder:
          brokers: ${KAFKA_ADDR:localhost}:${KAFKA_PORT:29092}
          auto-add-partitions: true
      bindings:
        output:
          destination: com.mycompany.userservice.user
          content-type: application/json # it's redundant here, 'application/json' is the default
          producer:
            partition-key-expression: headers['partitionKey']
            partition-count: 2
  sleuth:
    sampler.probability: 1.0
#    web.skipPattern: (^cleanup.*|.+favicon.*)

management:
  security.enabled: false
  endpoints:
    web:
      exposure.include: "*"
  endpoint:
    health:
      show-details: always

---
spring:
  profiles: avro
  cloud:
    stream:
      schema:
        avro:
          schema-locations:
            - classpath:avro/userevent-message.avsc
      bindings:
        output:
          content-type: application/*+avro

---
spring:
  profiles: test
  jpa:
    hibernate.ddl-auto: create-drop
  datasource:
    url: jdbc:mysql://localhost:3306/test-userdb?autoReconnect=true&useSSL=false&useUnicode=yes&characterEncoding=UTF-8&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: test-user
    password: test-pass
