management:
  security.enabled: false
  endpoints:
    web:
      exposure.include: "*"
  endpoint:
    health:
      show-details: always

spring:
  jpa:
    hibernate.ddl-auto: create
  datasource:
    url: jdbc:mysql://${MYSQL_ADDR:localhost}:3306/userdb?autoReconnect=true&useSSL=false&useUnicode=yes&characterEncoding=UTF-8&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: secret
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:29092
          auto-add-partitions: true
      bindings:
        user-output:
          destination: com.mycompany.userservice.user
          content-type: application/*+avro
          producer:
            partition-key-expression: headers['partitionKey']
            partition-count: 2
  sleuth:
    sampler.probability: 1.0
#    web.skipPattern: (^cleanup.*|.+favicon.*)