management:
  security.enabled: false
  endpoints.web.exposure.include: "*"
  endpoint.health.show-details: always

spring:
  jpa:
    hibernate.ddl-auto: create-drop
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${MYSQL_ADDR:localhost}:3306/userdb?autoReconnect=true&useSSL=false&useUnicode=yes&characterEncoding=UTF-8&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: secret
  cloud:
    stream.bindings:
      user:
        destination: com.mycompany.userservice.user
        content-type: application/*+avro
  sleuth:
    sampler.probability: 1.0
#    web.skipPattern: (^cleanup.*|.+favicon.*)