management:
  endpoint:
    health.show-details: always
  endpoints:
    web.exposure.include: health, httptrace

spring:
  data:
    cassandra:
      contactpoints: localhost
      port: 9042
      keyspace: mycompany
  cloud:
    stream.bindings:
      user:
        destination: com.mycompany.userservice.user
        content-type: application/*+avro
  sleuth:
    sampler.probability: 1.0
#    web.skipPattern: (^cleanup.*|.+favicon.*)