spring:
  data:
    cassandra:
      keyspace-name: mycompany
      contact-points: localhost
      port: 9042
      schema-action: CREATE_IF_NOT_EXISTS
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:29092
          auto-add-partitions: true
          min-partition-count: 2
      bindings:
        input:
          destination: com.mycompany.userservice.user
          content-type: application/json # it is redundant here because 'application/json' is the default
          group: eventServiceGroup
  sleuth:
    sampler.probability: 1.0
#    web.skipPattern: (^cleanup.*|.+favicon.*)

management:
  security.enabled: false
  endpoints:
    web:
      exposure.include: "*"
  endpoint:
    health:
      show-details: always

---
spring:
  profiles: avro
  cloud:
    stream:
      schema-registry-client:
        endpoint: http://localhost:8081
      bindings:
        input:
          content-type: application/*+avro # in fact, it is not needed because the converter gets the content type in the message header
