spring:
  data:
    cassandra:
      keyspace-name: mycompany
      contact-points: localhost
      port: 9042
      schema-action: CREATE_IF_NOT_EXISTS
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:29092
          auto-add-partitions: true
          min-partition-count: 2
      bindings:
        user-input:
          destination: com.mycompany.userservice.user
          content-type: application/avro
          group: eventServiceGroup
  sleuth:
    sampler.probability: 1.0
#    web.skipPattern: (^cleanup.*|.+favicon.*)

management:
  security.enabled: false
  endpoints:
    web:
      exposure.include: "*"
  endpoint:
    health:
      show-details: always
