management:
  security.enabled: false
  endpoints:
    web:
      exposure.include: "*"
  endpoint:
    health:
      show-details: always

spring:
  data:
    cassandra:
      contactpoints: localhost
      port: 9042
      keyspace: mycompany
  cloud:
    stream:
      kafka:
        binder:
          auto-add-partitions: true
          min-partition-count: 2
      bindings:
        user-input:
          destination: com.mycompany.userservice.user
          content-type: application/*+avro
          group: eventServiceGroup
  sleuth:
    sampler.probability: 1.0
#    web.skipPattern: (^cleanup.*|.+favicon.*)